# Generated by Django 4.0.2 on 2022-02-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
